### PR TITLE
017-Landing-Page-Ongoing-Maintenance

### PR DESCRIPTION
**Pull request by krisbitney**
Please chime in on estimates. I'm not sure how long some tasks will really take.

### CODE REVIEW

**Review by benefacto — CHANGES_REQUESTED** [review]
FYI, @krisbitney , I think @orishim 's intent behind this was to have a continuous budget that so that the backlog can be gradually worked through and newly requested changes have budget for them. So, more of a timeboxing model like $X/month and/or X hrs/month rather than budgeting for the specifically requested changes.

**Comment by orishim** [comment]
Yea this could be "Landing Page Maintenance Q2 '21" and have 10 hr / month x 3 months

**Review by benefacto — APPROVED** [review]

**Comment by krisbitney** [comment]
I updated the DSP

**Review by orishim — APPROVED** [review]

**Comment by orishim** [comment]
https://alchemy.daostack.io/dao/0x94a587478c83491b13291265581cb983e7feb540/proposal/0xaaff00a946a9519a1e749e30d7fc54cb525d48e8b483a912aea18b46f69fb78d

**Pull request merged**
