### PR TITLE
DSP-20: dOrg Retreat

### PR DESCRIPTION
**Pull request by benefacto**

### CODE REVIEW

**Comment by benefacto** [comment]
I can only select up to 15 reviewers...

**Comment by dOrgJelli** [comment]
How was the $1,000 number constructed? Could we create something based off of:
- X = Estimated # of people requiring subsidy
- Y = Estimated out of pocket funds
- Amount Requested = X * Y (if it's realistic and not too high)

$1,000 seems a little too small, but I'm unsure what the actual needs are of the people who want to attend.

**Comment by benefacto** [comment]
> 
> 
> How was the $1,000 number constructed? Could we create something based off of:
> 
>     * X = Estimated # of people requiring subsidy
> 
>     * Y = Estimated out of pocket funds
> 
>     * Amount Requested = X * Y (if it's realistic and not too high)
> 
> 
> $1,000 seems a little too small, but I'm unsure what the actual needs are of the people who want to attend.

Hey @dOrgJelli , thanks for the feedback. $1k was chosen arbitrarily and was mostly a political/accounting calculation based on the voting split and dOrg's reserve.
If we wanted to come up with a more objective sum, I think we would still run into the question of how much should dOrg cover since it probably cannot cover it all?

For example, this is what I envisioned as a high level estimate breakdown of the (average case) out of pocket expenses for a builder (max range includes a plus one):
- Food: $245-$490 (~$35/day/person)
- Lodging: $560-$1120 (~$80/night/person)
- Travel: $600-$1200 (round trip flight: ~$600/person)
Total cost per builder: $1405- $2810
The total costs could be (assuming 25 builders): $35,125 - $70,250
The total costs of those desiring subsidy (14) could be: $19,670-$39,340
The total costs of those desiring no out-of-pocket costs (3) could be: $4215-$8430

Because of the significant out-of-pocket costs for builders, it seemed like to me that any subsidy was ultimately going to be arbitrary since dOrg's current reserve would not be able to meaningfully impact it.
That said, I'm definitely open to suggestion on what the right number for a subsidy should be. 
The reason I chose lodging was because it is something that we could easily save on by selecting a large venue and it seems fairer than subsidizing travel since that could vary significantly depending on where builders are coming from.

**Comment by krisbitney** [comment]
Instead of subsidizing lodging, what if we instead used funding for team-building activities? The costs of lodging can vary considerably depending on quality, location, and related individual preferences. I think it could make more sense to plan a few activities and subsidize those costs to ensure everyone can participate.

We can still select a hotel or AirBnB and encourage everyone to stay there or nearby. The members staying there can pool money to reserve and pay for it. I would be happy to join in.

Are we sure we need to subsidize any part of the retreat? Maybe we should keep this informal and save dOrg's budget?

P.S. looking forward to meeting you all!

**Comment by Remscar** [comment]
> Instead of subsidizing lodging, what if we instead used funding for team-building activities? The costs of lodging can vary considerably depending on quality, location, and related individual preferences. I think it could make more sense to plan a few activities and subsidize those costs to ensure everyone can participate.
> 
> We can still select a hotel or AirBnB and encourage everyone to stay there or nearby. The members staying there can pool money to reserve and pay for it. I would be happy to join in.
> 
> Are we sure we need to subsidize any part of the retreat? Maybe we should keep this informal and save dOrg's budget?
> 
> P.S. looking forward to meeting you all!

I agree with the sentiment of using the money to pay for team building activities, or a team-related event as being better idea here instead of subsidizing travel/lodging expenses. This way dOrg can pay for an activity that we all vote and decide on doing, and it will be cheaper for dOrg probably and more impactful for individual members. (I was going to pay for airfare/room anyways, I wasn't necessarily going to do a tapas crawl through Madrid but since dOrg is paying for it an all my fellow dOrg-er's are going, it sounds like a great chance to meet them all)

**Comment by benefacto** [comment]
These are great points. It sounds like dOrg's reserve could go further by funding team building activities rather than doing a negligible subsidy of lodging.

**Comment by krisbitney** [comment]
I don't know how much research, planning, and communication needs to be done, but does it make sense to request some funding for yourself @benefacto to more formally coordinate the retreat (if you're up for that)? You're already taking the lead on this and making it real, which I personally very much appreciate.

**Comment by benefacto** [comment]
> 
> 
> I don't know how much research, planning, and communication needs to be done, but does it make sense to request some funding for yourself @benefacto to more formally coordinate the retreat (if you're up for that)? You're already taking the lead on this and making it real, which I personally very much appreciate.

Thanks, guys. I created a modest coordination budget so that anyone who's doing coordination can make claims on it.

**Comment by benefacto** [comment]
Closing out this DSP for now as per [the latest budget report](https://discord.com/channels/544647726982365194/803414189103513641/848994007559569440)

**Pull request closed without merging**
